name: Build CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: install gulp
        run: npm install --global gulp-cli
      - name: install dependencies
        run: npm install --save-dev
      - name: list dependencies
        run: npm list
      - name: run tests
        run: gulp test
