name: Build CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
defaults:
  run:
    working-directory: react
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Start server and run all tests with coverage
        run: npm start & sleep 60; npm run coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/coverage-final.json
#            - name: Build & Deploy
#              run: |
#                  git remote set-url origin https://${github_token}@github.com/${repository}/
#                  npm run deploy
#              env:
#                  github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
#                  repository: ${{ github.repository }}
